### ISSUE TITLE
localhost refused to connect.

### ISSUE THREAD

**Issue by 4tegarrrrrrrrr** [HamsterHelper/HamsterHelper#2]
![image](https://github.com/HamsterHelper/HamsterHelper/assets/148928172/9e5e838b-f439-474f-842b-b636692f232c)
![image](https://github.com/HamsterHelper/HamsterHelper/assets/148928172/ad4462ed-6d69-4cf1-9901-cd2fd2fb7e52)

**Comment by HamsterHelper** [comment]
教程写了
